---
output: 
    stevetemplates::statement:
    latex_engine: pdflatex
geometry: margin=1in
title: "Course Outline: BHR 210- Statistics"
author: John Karuitha
affiliation: Department of Business & Economics, Karatina University
email: "jkaruitha@karu.ac.ke"
phone: "+254 736 917 717"
params: 
    course: "BHR 210: STATISTICS II- HR"
fontfamily: cochineal
fontsize: 12pt
---

## COURSE OUTLINE: `r params$course` 

## COURSE PURPOSE
The course aims at equipping the student with skills in statistical analysis for making decisions. The course does so by building allowing students to build an intuition instead of merely plugging numbers into formula.

## COURSE LEARNING OUTCOMES
At the end of the course, the learner should be able to;

1. Define statistics and data.
2. Distinguish between the various data types.
2. Master the Basics of R programming language for statistical analysis.
2. Visualize data manually and using R.
3. Summarize qualitative and quantitative data.
4. Evaluate the strength of association between variables.
5. Make inference using data.
6. Build basic regression models.
7. Create a statistical analysis report in R Markdown. 

## COURSE CONTENT

- Exploring and collecting data.
    - Definitions and background.
    - Statistics and Variation.
    - Data: Data types and Sources.
    - Surveys and Sampling.
    - Introduction to R and R-Studio.
    
- Data Visualization.
    - Displaying and describing categorical data.
    - Displaying and describing quantitative data.
    - Plotting data in base R.
    - Introduction to the Tidyverse and GGPLOT plotting in R.
    
- Summarizing data.
    - Summarizing categorical data.
    - Summarizing quantitative data.
        - Measures of center.
        - Measures of spread.
    - Summarizing data using R and the Tidyverse.
    
- Report Writing in Statistics
    - Elements of a statistics based report.
    - Introduction to latex, knitr, and R Markdown. 
    - Writing a statistics based report in R Markdown. 

- Randomness and probability. 
    - Random phenomena and probability.
    - The non-existent law of averages.
    - Different types of probability.
    - Probability rules.
    - Joint probability and contingency tables.
    - Conditional probability.
    - Constructing contingency tables.
    
- Random variables and probability models.
    - Expected value of a random variable.
    - Standard deviation of a random variable.
    - Properties of expected values and variances.
    - Discrete probability distributions.
    
- The normal distribution.

- Parametric Inference for decision making. 
    - Testing hypotheses.
    - Comparing two groups.
    - Inference for counts: The Chi- Square tests.

## MODE OF DELIVERY OF THE COURSE
The course will be delivered using a combination of online lectures, discussions based on case studies and presentations by students.

## INSTRUCTIONAL MATERIALS/ EQUIPMENT
- I have made arrangements that technicians at the computers labs at the University install `R` and `R Studio` on the computers.  

- For students who own personal computers please install both `R` and `R studio` from the internet. Confirm whether your computer is 32-bit or 64 bit and install the appropriate version. Each software is free. 

- `R` is availabe on this link <https://cran.r-project.org/bin/windows/base/>.

- `R_Studio` is available on this link <https://rstudio.com/products/rstudio/download/>.

- Both `R` and `R-Studio` are available for Mac, Linux, and Windows based systems. Choose the appropriate version for your computer. 

- For students who own tablets, you can neither install `R` nor `R Studio`. However, you can access the service online through `R Studio Cloud`. You have to be connected to the internet to access and use this service. Students with personal computers may also opt for this route. 

## COURSE ASSESSMENT
The course will be assessed through a combination of continuous assessment tests, project based class assignments and final exam as follows.

```{r, echo = FALSE}
library(tidyverse)
library(tibble)
tribble(~ Assessment, ~ Contribution,
        "CAT 1: Multiple Choice", "5%",
        "CAT 2: Multiple Choice", "5%",
        "CAT 3: Sit in: Essays and Computations", "10%",
        "CAT 4: Statistics based project report", "10%")
``